[uwsgi]
module=main.wsgi:application
master=True
; pidfile=/tmp/django-master.pid
vacuum=True
max-requests=5000
; daemonize=log/app.log
http=:8000
; %d = absolute path of the directory containing this config file (trailing slash)
static-map = /static=%dstatic
static-gzip-all = true
