# Generated by Django 5.2.16 on 2026-07-14

import django.core.validators
from django.db import migrations, models
from django.db.models import Q


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CVE",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cve_id",
                    models.CharField(
                        help_text="CVE-YYYY-NNNN format",
                        max_length=32,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="CVE ID must use the format CVE-YYYY-NNNN.",
                                regex="^CVE-\\d{4}-\\d{4,}$",
                            )
                        ],
                    ),
                ),
                ("source_identifier", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_modified_at", models.DateTimeField(blank=True, null=True)),
                ("vuln_status", models.CharField(blank=True, max_length=64)),
                ("cvss_version", models.CharField(blank=True, max_length=16)),
                ("cvss_vector", models.CharField(blank=True, max_length=255)),
                (
                    "cvss_base_score",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=3,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "cvss_base_severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NONE", "None"),
                            ("LOW", "Low"),
                            ("MEDIUM", "Medium"),
                            ("HIGH", "High"),
                            ("CRITICAL", "Critical"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "cwe_ids",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated CWE identifiers, for example CWE-79,CWE-89.",
                        max_length=1000,
                    ),
                ),
                ("reference_urls", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CVE",
                "verbose_name_plural": "CVEs",
                "ordering": ["-published_at", "cve_id"],
                "indexes": [
                    models.Index(fields=["published_at"], name="cve_published_idx"),
                    models.Index(fields=["last_modified_at"], name="cve_modified_idx"),
                    models.Index(fields=["cvss_base_severity"], name="cve_severity_idx"),
                    models.Index(fields=["vuln_status"], name="cve_status_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=Q(cvss_base_score__isnull=True)
                        | Q(cvss_base_score__gte=0, cvss_base_score__lte=10),
                        name="cve_cvss_score_range",
                    )
                ],
            },
        ),
    ]
